# Generated by Django 3.2.8 on 2021-11-02 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Autor', 'verbose_name_plural': 'Autores'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Libro'},
        ),
        migrations.AddField(
            model_name='book',
            name='fecha',
            field=models.DateField(auto_now=True, help_text='Fecha de publicación'),
        ),
        migrations.AlterField(
            model_name='author',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha nacimiento'),
        ),
    ]
