# Generated by Django 3.2.8 on 2021-11-16 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imagenes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagen',
            name='alto',
        ),
        migrations.RemoveField(
            model_name='imagen',
            name='ancho',
        ),
        migrations.RemoveField(
            model_name='imagen',
            name='fecha_subida',
        ),
        migrations.RemoveField(
            model_name='imagen',
            name='subida_por',
        ),
    ]
