# Generated by Django 3.2.8 on 2021-11-16 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('imagenes', '0002_auto_20211116_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagen',
            name='alto',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='imagen',
            name='ancho',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='imagen',
            name='fecha_subida',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Fecha de subida'),
        ),
        migrations.AddField(
            model_name='imagen',
            name='subida_por',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Subida por usuario'),
        ),
    ]
